// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VolunteerMatch.Models;

#nullable disable

namespace VolunteerMatch.Migrations
{
    [DbContext(typeof(VolunteerMatchingDbContext))]
    partial class VolunteerMatchingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VolunteerMatch.Models.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("AgeMax")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("AgeMin")
                        .HasColumnType("tinyint");

                    b.Property<string>("Benefits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpeakersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("EventId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("VolunteerMatch.Models.EventTag", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EventId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("EventTags");
                });

            modelBuilder.Entity("VolunteerMatch.Models.FavoriteEvent", b =>
                {
                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.HasKey("VolunteerId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("FavoriteEvents");
                });

            modelBuilder.Entity("VolunteerMatch.Models.MatchingSuggestion", b =>
                {
                    b.Property<Guid>("SuggestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Initiator")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("MatchScore")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("OrganizationApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool?>("VolunteerApproved")
                        .HasColumnType("bit");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SuggestionId");

                    b.HasIndex("EventId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("MatchingSuggestions");
                });

            modelBuilder.Entity("VolunteerMatch.Models.OrganizationComment", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("AuthorVolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("StarRating")
                        .HasColumnType("tinyint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("CommentId");

                    b.HasIndex("AuthorVolunteerId");

                    b.HasIndex(new[] { "OrganizationId", "AuthorVolunteerId" }, "UQ_OrganizationComment")
                        .IsUnique();

                    b.ToTable("OrganizationComments");
                });

            modelBuilder.Entity("VolunteerMatch.Models.OrganizationProfile", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("OrganizationId");

                    b.ToTable("OrganizationProfiles");
                });

            modelBuilder.Entity("VolunteerMatch.Models.Permission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PermissionId");

                    b.HasIndex(new[] { "PermissionName" }, "UQ_Permissions_Name")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("VolunteerMatch.Models.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TagId");

                    b.HasIndex(new[] { "Name" }, "UQ_Tags_Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("VolunteerMatch.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VolunteerMatch.Models.UserPermission", b =>
                {
                    b.Property<Guid>("UserPermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserPermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex(new[] { "UserId", "PermissionId" }, "UQ_UserPermissions")
                        .IsUnique();

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("VolunteerMatch.Models.VolunteerComment", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("AuthorOrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.Property<byte>("StarRating")
                        .HasColumnType("tinyint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommentId");

                    b.HasIndex("AuthorOrganizationId");

                    b.HasIndex(new[] { "VolunteerId", "AuthorOrganizationId" }, "UQ_VolunteerComment")
                        .IsUnique();

                    b.ToTable("VolunteerComments");
                });

            modelBuilder.Entity("VolunteerMatch.Models.VolunteerProfile", b =>
                {
                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Technologies")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("VolunteerId");

                    b.ToTable("VolunteerProfiles");
                });

            modelBuilder.Entity("VolunteerMatch.Models.VolunteerTag", b =>
                {
                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VolunteerId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("VolunteerTags");
                });

            modelBuilder.Entity("VolunteerMatch.Models.Event", b =>
                {
                    b.HasOne("VolunteerMatch.Models.OrganizationProfile", "Organization")
                        .WithMany("Events")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK_Events_Organization");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("VolunteerMatch.Models.EventTag", b =>
                {
                    b.HasOne("VolunteerMatch.Models.Event", "Event")
                        .WithMany("EventTags")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK_EventTags_Event");

                    b.HasOne("VolunteerMatch.Models.Tag", "Tag")
                        .WithMany("EventTags")
                        .HasForeignKey("TagId")
                        .IsRequired()
                        .HasConstraintName("FK_EventTags_Tag");

                    b.Navigation("Event");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("VolunteerMatch.Models.FavoriteEvent", b =>
                {
                    b.HasOne("VolunteerMatch.Models.Event", "Event")
                        .WithMany("FavoriteEvents")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK_FavoriteEvents_Event");

                    b.HasOne("VolunteerMatch.Models.VolunteerProfile", "Volunteer")
                        .WithMany("FavoriteEvents")
                        .HasForeignKey("VolunteerId")
                        .IsRequired()
                        .HasConstraintName("FK_FavoriteEvents_Volunteer");

                    b.Navigation("Event");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("VolunteerMatch.Models.MatchingSuggestion", b =>
                {
                    b.HasOne("VolunteerMatch.Models.Event", "Event")
                        .WithMany("MatchingSuggestions")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK_MS_Event");

                    b.HasOne("VolunteerMatch.Models.VolunteerProfile", "Volunteer")
                        .WithMany("MatchingSuggestions")
                        .HasForeignKey("VolunteerId")
                        .IsRequired()
                        .HasConstraintName("FK_MS_Volunteer");

                    b.Navigation("Event");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("VolunteerMatch.Models.OrganizationComment", b =>
                {
                    b.HasOne("VolunteerMatch.Models.VolunteerProfile", "AuthorVolunteer")
                        .WithMany("OrganizationComments")
                        .HasForeignKey("AuthorVolunteerId")
                        .IsRequired()
                        .HasConstraintName("FK_OC_AuthorVolunteer");

                    b.HasOne("VolunteerMatch.Models.OrganizationProfile", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorVolunteer");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("VolunteerMatch.Models.OrganizationProfile", b =>
                {
                    b.HasOne("VolunteerMatch.Models.User", "Organization")
                        .WithOne("OrganizationProfile")
                        .HasForeignKey("VolunteerMatch.Models.OrganizationProfile", "OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK_OrganizationProfiles_Users");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("VolunteerMatch.Models.UserPermission", b =>
                {
                    b.HasOne("VolunteerMatch.Models.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .IsRequired()
                        .HasConstraintName("FK_UP_Permission");

                    b.HasOne("VolunteerMatch.Models.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UP_User");

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VolunteerMatch.Models.VolunteerComment", b =>
                {
                    b.HasOne("VolunteerMatch.Models.OrganizationProfile", "AuthorOrganization")
                        .WithMany()
                        .HasForeignKey("AuthorOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolunteerMatch.Models.VolunteerProfile", "Volunteer")
                        .WithMany("VolunteerComments")
                        .HasForeignKey("VolunteerId")
                        .IsRequired()
                        .HasConstraintName("FK_VC_Volunteer");

                    b.Navigation("AuthorOrganization");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("VolunteerMatch.Models.VolunteerProfile", b =>
                {
                    b.HasOne("VolunteerMatch.Models.User", "Volunteer")
                        .WithOne("VolunteerProfile")
                        .HasForeignKey("VolunteerMatch.Models.VolunteerProfile", "VolunteerId")
                        .IsRequired()
                        .HasConstraintName("FK_VolunteerProfiles_Users");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("VolunteerMatch.Models.VolunteerTag", b =>
                {
                    b.HasOne("VolunteerMatch.Models.Tag", "Tag")
                        .WithMany("VolunteerTags")
                        .HasForeignKey("TagId")
                        .IsRequired()
                        .HasConstraintName("FK_VolunteerTags_Tag");

                    b.HasOne("VolunteerMatch.Models.VolunteerProfile", "Volunteer")
                        .WithMany("VolunteerTags")
                        .HasForeignKey("VolunteerId")
                        .IsRequired()
                        .HasConstraintName("FK_VolunteerTags_Volunteer");

                    b.Navigation("Tag");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("VolunteerMatch.Models.Event", b =>
                {
                    b.Navigation("EventTags");

                    b.Navigation("FavoriteEvents");

                    b.Navigation("MatchingSuggestions");
                });

            modelBuilder.Entity("VolunteerMatch.Models.OrganizationProfile", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("VolunteerMatch.Models.Permission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("VolunteerMatch.Models.Tag", b =>
                {
                    b.Navigation("EventTags");

                    b.Navigation("VolunteerTags");
                });

            modelBuilder.Entity("VolunteerMatch.Models.User", b =>
                {
                    b.Navigation("OrganizationProfile");

                    b.Navigation("UserPermissions");

                    b.Navigation("VolunteerProfile");
                });

            modelBuilder.Entity("VolunteerMatch.Models.VolunteerProfile", b =>
                {
                    b.Navigation("FavoriteEvents");

                    b.Navigation("MatchingSuggestions");

                    b.Navigation("OrganizationComments");

                    b.Navigation("VolunteerComments");

                    b.Navigation("VolunteerTags");
                });
#pragma warning restore 612, 618
        }
    }
}
